# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hyperliquid_trading_agent.app.liquidations.adapters.proto import hyperliquid_l1_gateway_pb2 as hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hyperliquid_trading_agent/app/liquidations/adapters/proto/hyperliquid_l1_gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HyperliquidL1GatewayStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamBlocks = channel.unary_stream(
                '/hyperliquid_l1_gateway.v2.HyperliquidL1Gateway/StreamBlocks',
                request_serializer=hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.Position.SerializeToString,
                response_deserializer=hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.Block.FromString,
                _registered_method=True)
        self.StreamFills = channel.unary_stream(
                '/hyperliquid_l1_gateway.v2.HyperliquidL1Gateway/StreamFills',
                request_serializer=hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.Position.SerializeToString,
                response_deserializer=hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.BlockFills.FromString,
                _registered_method=True)
        self.StreamOrderbookSnapshots = channel.unary_stream(
                '/hyperliquid_l1_gateway.v2.HyperliquidL1Gateway/StreamOrderbookSnapshots',
                request_serializer=hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.Position.SerializeToString,
                response_deserializer=hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.OrderBookSnapshot.FromString,
                _registered_method=True)
        self.GetBlock = channel.unary_unary(
                '/hyperliquid_l1_gateway.v2.HyperliquidL1Gateway/GetBlock',
                request_serializer=hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.Position.SerializeToString,
                response_deserializer=hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.Block.FromString,
                _registered_method=True)
        self.GetFills = channel.unary_unary(
                '/hyperliquid_l1_gateway.v2.HyperliquidL1Gateway/GetFills',
                request_serializer=hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.Position.SerializeToString,
                response_deserializer=hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.BlockFills.FromString,
                _registered_method=True)
        self.GetOrderBookSnapshot = channel.unary_unary(
                '/hyperliquid_l1_gateway.v2.HyperliquidL1Gateway/GetOrderBookSnapshot',
                request_serializer=hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.Timestamp.SerializeToString,
                response_deserializer=hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.OrderBookSnapshot.FromString,
                _registered_method=True)


class HyperliquidL1GatewayServicer:
    """Missing associated documentation comment in .proto file."""

    def StreamBlocks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFills(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamOrderbookSnapshots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFills(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderBookSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HyperliquidL1GatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamBlocks': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamBlocks,
                    request_deserializer=hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.Position.FromString,
                    response_serializer=hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.Block.SerializeToString,
            ),
            'StreamFills': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFills,
                    request_deserializer=hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.Position.FromString,
                    response_serializer=hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.BlockFills.SerializeToString,
            ),
            'StreamOrderbookSnapshots': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamOrderbookSnapshots,
                    request_deserializer=hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.Position.FromString,
                    response_serializer=hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.OrderBookSnapshot.SerializeToString,
            ),
            'GetBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBlock,
                    request_deserializer=hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.Position.FromString,
                    response_serializer=hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.Block.SerializeToString,
            ),
            'GetFills': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFills,
                    request_deserializer=hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.Position.FromString,
                    response_serializer=hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.BlockFills.SerializeToString,
            ),
            'GetOrderBookSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderBookSnapshot,
                    request_deserializer=hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.Timestamp.FromString,
                    response_serializer=hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.OrderBookSnapshot.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hyperliquid_l1_gateway.v2.HyperliquidL1Gateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hyperliquid_l1_gateway.v2.HyperliquidL1Gateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HyperliquidL1Gateway:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamBlocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hyperliquid_l1_gateway.v2.HyperliquidL1Gateway/StreamBlocks',
            hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.Position.SerializeToString,
            hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.Block.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFills(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hyperliquid_l1_gateway.v2.HyperliquidL1Gateway/StreamFills',
            hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.Position.SerializeToString,
            hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.BlockFills.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamOrderbookSnapshots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hyperliquid_l1_gateway.v2.HyperliquidL1Gateway/StreamOrderbookSnapshots',
            hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.Position.SerializeToString,
            hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.OrderBookSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperliquid_l1_gateway.v2.HyperliquidL1Gateway/GetBlock',
            hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.Position.SerializeToString,
            hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.Block.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFills(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperliquid_l1_gateway.v2.HyperliquidL1Gateway/GetFills',
            hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.Position.SerializeToString,
            hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.BlockFills.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderBookSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperliquid_l1_gateway.v2.HyperliquidL1Gateway/GetOrderBookSnapshot',
            hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.Timestamp.SerializeToString,
            hyperliquid__trading__agent_dot_app_dot_liquidations_dot_adapters_dot_proto_dot_hyperliquid__l1__gateway__pb2.OrderBookSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
