# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hyperliquid_trading_agent/app/liquidations/adapters/proto/hyperliquid_l1_gateway.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'hyperliquid_trading_agent/app/liquidations/adapters/proto/hyperliquid_l1_gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nVhyperliquid_trading_agent/app/liquidations/adapters/proto/hyperliquid_l1_gateway.proto\x12\x19hyperliquid_l1_gateway.v2\"F\n\x08Position\x12\x16\n\x0ctimestamp_ms\x18\x01 \x01(\x03H\x00\x12\x16\n\x0c\x62lock_height\x18\x02 \x01(\x03H\x00\x42\n\n\x08position\"!\n\tTimestamp\x12\x14\n\x0ctimestamp_ms\x18\x01 \x01(\x03\"\x1a\n\nBlockFills\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x15\n\x05\x42lock\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"!\n\x11OrderBookSnapshot\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\xd4\x04\n\x14HyperliquidL1Gateway\x12W\n\x0cStreamBlocks\x12#.hyperliquid_l1_gateway.v2.Position\x1a .hyperliquid_l1_gateway.v2.Block0\x01\x12[\n\x0bStreamFills\x12#.hyperliquid_l1_gateway.v2.Position\x1a%.hyperliquid_l1_gateway.v2.BlockFills0\x01\x12o\n\x18StreamOrderbookSnapshots\x12#.hyperliquid_l1_gateway.v2.Position\x1a,.hyperliquid_l1_gateway.v2.OrderBookSnapshot0\x01\x12Q\n\x08GetBlock\x12#.hyperliquid_l1_gateway.v2.Position\x1a .hyperliquid_l1_gateway.v2.Block\x12V\n\x08GetFills\x12#.hyperliquid_l1_gateway.v2.Position\x1a%.hyperliquid_l1_gateway.v2.BlockFills\x12j\n\x14GetOrderBookSnapshot\x12$.hyperliquid_l1_gateway.v2.Timestamp\x1a,.hyperliquid_l1_gateway.v2.OrderBookSnapshotb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hyperliquid_trading_agent.app.liquidations.adapters.proto.hyperliquid_l1_gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSITION']._serialized_start=117
  _globals['_POSITION']._serialized_end=187
  _globals['_TIMESTAMP']._serialized_start=189
  _globals['_TIMESTAMP']._serialized_end=222
  _globals['_BLOCKFILLS']._serialized_start=224
  _globals['_BLOCKFILLS']._serialized_end=250
  _globals['_BLOCK']._serialized_start=252
  _globals['_BLOCK']._serialized_end=273
  _globals['_ORDERBOOKSNAPSHOT']._serialized_start=275
  _globals['_ORDERBOOKSNAPSHOT']._serialized_end=308
  _globals['_HYPERLIQUIDL1GATEWAY']._serialized_start=311
  _globals['_HYPERLIQUIDL1GATEWAY']._serialized_end=907
# @@protoc_insertion_point(module_scope)
